### ISSUE TITLE
react-map-gl components no longer working with Amplify UI Geo

### ISSUE THREAD

**Issue by imraymondlee** [aws-amplify/amplify-ui#1906]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### Please describe your bug.

I've upgraded to @aws-amplify/ui-react v2.17.1 and I am seeing issues with Amplify UI Geo components where I can no longer use `react-map-gl` components. So far I have tried using the `Marker`, `Popup`, `NavigationControl`, `Source`, and `Layer` components. It is causing an error and preventing the app from running. Based on the error, it looks like that react-map-gl can no longer get the `MapContext`

```
Uncaught TypeError: Cannot destructure property 'map' of '(0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...)' as it is null.
    at Marker (marker.ts:87:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
```

### What's the expected behaviour?

react-map-gl components should be compatible with Amplify UI's MapView component.

### Help us reproduce the bug!

1. Create an app using @aws-amplify/ui-react v2.17.1
2. Display a map using the Amplify UI MapView component and react-map-gl Marker component
3. The app will not run and there will be errors in the console

### Code Snippet

```typescript
function App() {
  return (
    <MapView>
      <Marker latitude={37.8} longitude={-122.4} />
    </MapView>
  );
}

```

**Comment by MattJColes** [comment]
Am seeing the same thing also. Updated all my dependencies and the cli and still have this issue also. It looks like the structure for geo has changed within the amplify exports folder which i suspect is why we see this error.

**Comment by slaymance** [comment]
This is a bug we've accidentally introduced in our change to [point react-map-gl to the ES5 bundle](https://github.com/aws-amplify/amplify-ui/pull/1887). We're actively looking to introduce a fix. In the meantime, you can workaround this bug by importing `react-map-gl` modules from the ES5 dist:
```jsx
import { MapView } from '@aws-amplify/ui-react';
import { Marker } from 'react-map-gl/dist/es5';

...

function App() {
  return (
    <MapView>
      <Marker latitude={37.8} longitude={-122.4} />
    </MapView>
  );
}
```

**Comment by joebuono** [comment]
Resolved with latest release: https://github.com/aws-amplify/amplify-ui/pull/1897

**Comment by aspittel** [comment]
I'm seeing this issue right now:

```js
{
  "name": "amplify-ui-prelaunch",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^3.0.4",
    "aws-amplify": "^4.3.26",
    "next": "12.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-map-gl": "^7.0.17",
    "standard": "^17.0.0"
  }
}
```

**Comment by aspittel** [comment]
Update: if you run into this,  uninstall `react-map-gl` and re-install `@aws-amplify/ui-react`

**Comment by entest-hai** [comment]
The issue is not yet solved. I experience the same problem. 
```json 
 "dependencies": {
    "@aws-amplify/ui-react": "^3.0.4",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.27",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-map-gl": "^7.0.17",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

MapView
```js
<MapView
  initialViewState={{
    longitude: -122.3381659,
    latitude: 47.615686,
    zoom: 12,
    }}
  style={{ width: '600px', height: '600px' }}
  >
      {locationData.map((loc) => (
      <Marker
	      latitude={loc.latitude}
	      longitude={loc.longitude}
	      key={loc.id}
      >
      </Marker>
  ))}
  </MapView>
```

**Comment by messmacher** [comment]
> `uninstall react-map-gl` and re-install `@aws-amplify/ui-react`
Continue experiencing the problem even after uninstalling react-map-gl and re-installing `@aws-amplify/ui-react`

**Comment by entest-hai** [comment]
@messmacher thank you! it works now.
