### ISSUE TITLE
Amplify ui breaks Vuetify styling

### ISSUE THREAD

**Issue by ClaudioVR** [aws-amplify/amplify-ui#824]
I am working on a Vue.js application and I am using Vuetify for the styling.

I am also using the amplify authenticator and importing as stated in the docs.

My main.js file looks like this:

```
import Vue from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";
import vuetify from "./plugins/vuetify";
import {
  applyPolyfills,
  defineCustomElements,
} from "@aws-amplify/ui-components/loader";

import Amplify from "aws-amplify";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

applyPolyfills().then(() => {
  defineCustomElements(window);
});

Vue.config.ignoredElements = [/amplify-\w*/];

Vue.config.productionTip = false;


new Vue({
  router,
  store,
  vuetify,
  render: (h) => h(App),
}).$mount("#app");
```

All works fine with the authenticator however, a number of small but vital parts of the Vuetify styling seem to break. 
If I comment out the amplifyUI bits from my main.js, the Vuetify styling works just fine. 

Examples of styling that breaks are the grid:

The columns will not center property

```  
<v-row>
  <v-col
    cols="12"
    sm="8"
    offset-sm="2"
    md="6"
    offset-md="3"
    xl="4"
    offset-xl="4"
  >
    <router-view />
  </v-col>
</v-row>
```
    
Another example is the v-card-text breaking the v-card boundaries on the right side:
```
  <v-card class="red">
    <v-card-text class="blue"></v-card-text>
  </v-card>
```
    
  ...and so forth.
  
  I have been able to apply some corrections to the styling on the v-card, but trying to correct the responsive grid is more complex and time consuming. There may also be other breaks that I have not come across yet.
  
  Are others out there experiencing the same problem? Does anyone know of a solution?
  
  Using the amplify authenticator is a must for this project, but it is making working with Vuetify (our fav UI library) a bit of a nightmare.
  
  Many thanks in advance.

**Comment by ClaudioVR** [comment]
Example of a grid working properly with ampliyUI imports in main.js commented out:

![image](https://user-images.githubusercontent.com/42936120/142858318-a1054fb0-3a8a-4874-ab3f-7155a35c903e.png)

and what happens when amplifyUI is uncommented and breaks vuetify styling:

NB: notice that elements breach the column, and the red column is not centered in the green row.
![image](https://user-images.githubusercontent.com/42936120/142858568-8d9d75b7-b735-4f01-8bac-faa743cb5a94.png)

**Comment by ClaudioVR** [comment]
I seem to have solved the issue.

My App.vue file looked something like this:

```
 <amplify-auth-container >
    <amplify-authenticator >
       <v-app>
          <v-main> ... </v-main>
       </v-app>
    </amplify-authenticator>
 </amplify-auth-container>
```

I have since changed it to the following and the styling as well as the authentication flow seems to work correctly...

```
    <amplify-auth-container v-if="authState !== 'signedin'">
      <amplify-authenticator username-alias="email"></amplify-authenticator>
    </amplify-auth-container>

    <v-app v-if="authState === 'signedin' && user">
      <v-main>
        <v-container>
          <router-view />
        </v-container>
      </v-main>
    </v-app>
```

It would still be interesting to have some feedback as to what might have been happening...

**Comment by ericclemmons** [comment]
@ClaudioVR It looks like you're using the v1 release & on Thursday we published a v2 to address several styling & functional issues.

Can you share your experience with that version? 🙏 
> https://ui.docs.amplify.aws/components/authenticator?platform=vue#quick-start

**Comment by ClaudioVR** [comment]
@ericclemmons I have updated my dependencies but the Authenticator ui does not seem to have changed. I followed the Vue 2 docs without any luck.

My package.json looks like this (p.s: have deleted node modules and re run npm install). Amplify CLI is also updated to latest version.

```
  "dependencies": {
    "@aws-amplify/ui-components": "^1.9.6",
    "aws-amplify": "^4.3.6",
    "core-js": "^3.6.5",
    "register-service-worker": "^1.7.1",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuetify": "^2.6.0",
    "vuex": "^3.4.0"
  },
  ```
  
  Despite the UI not having changed, I still faced the same issue as mentioned above when wrapping my v-app with the authenticator component.

**Comment by ErikCH** [comment]
Hi @ClaudioVR ! I'm glad you figured out a work around for now. 

The new `@aws-amplify/ui-vue` library only works for Vue 3, so it won't help in the situation you're in unfortunately. So feel free to remove it from your package.json. Have you looked into Vue 3?

The `@aws-amplify/ui-components` will work fine for Vue 2 though. There might be some slight issues with the `ui-components` library and how the shadow dom works. 

For now I suggest use the work around you found.

**Comment by Milan-Shah** [comment]
@ClaudioVR We are glad that you have found a work around solution for your needs. Feel free to create another issue if you would like to suggest any improvements or have an issue. We are here to help :)

**Comment by ClaudioVR** [comment]
@ErikCH Thanks. I'll be upgrading to Vue3 as soon as Vuetify3 is up and running. 

I came across a recent video you made on youtube: "How To Add Authentication To Your App In 5 Minutes" which was very helpful. Look forward to applying it to my project in near future.

**Comment by ErikCH** [comment]
Thanks @ClaudioVR ! Glad it helped.
